name: ItemInventory
version: '1.0-SNAPSHOT'
main: me.iteminventory.ItemInventory
authors: [ FIP ]
description: Idk
api-version: 1.13
commands:
  iteminventory:
    description: iteminventory
permissions:
  iteminventory:
    default: op
    children:
      iteminventory.reload:
        description: reload config
        default: op
      iteminventory.check:
        description: check all player
        default: op